### ISSUE TITLE
Can't install with Python 3.12.2

### ISSUE THREAD

**Issue by mihaitodor** [davep/oshit#23]
Hey, I just replaced my laptop and got a bit stuck. I did `brew install python3 pipx` which installed Python 3.12.2 and pipx 1.4.3 and then I got this error when trying to install `oshit`:

```
> pipx install oshit
Fatal error from pip prevented installation. Full pip output in file:
    /Users/mihaitodor/Library/Logs/pipx/cmd_2024-02-27_17.46.16_pip_errors.log

Some possibly relevant errors from pip install:
    ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python <3.12,>=3.10; 0.0.2 Requires-Python <3.12,>=3.10; 0.1.0 Requires-Python <3.12,>=3.10; 0.1.1 Requires-Python <3.12,>=3.10; 0.2.0 Requires-Python <3.12,>=3.10; 0.3.0 Requires-Python <3.12,>=3.10; 0.4.0 Requires-Python <3.12,>=3.10; 0.5.0 Requires-Python <3.12,>=3.10; 0.6.0 Requires-Python <3.12,>=3.10; 0.7.0 Requires-Python <3.12,>=3.10; 0.8.0 Requires-Python <3.12,>=3.10; 0.9.0 Requires-Python <3.12,>=3.10
    ERROR: Could not find a version that satisfies the requirement oshit (from versions: none)
    ERROR: No matching distribution found for oshit

Error installing oshit.
```

**Comment by davep** [comment]
That would be correct, it's currently packaged to exclude use of Python 3.12 (as I kept noticing some dependency issues with 3.12).

Ideally you wouldn't install Python using homebrew, generally. This probably needs a refresh [but I'd normally advise using `pyenv` to manage the installation of Python](https://blog.davep.org/2022/11/05/python-and-macos.html); then when it comes to initially installing a package with `pipx` [you can guide it to a reasonable version](https://stackoverflow.com/questions/68735503/how-does-pipx-know-which-python-version-to-use).

(It seems to me that it's one of the many issues with Python packaging and distribution that `pipx` can't do the right thing based on the specified Python version of the thing you're installing).

At some point soon I'll do a fresh test with 3.12; but even quiet recently `pipx` (or something it relied on) did a terrible job of installing this (and anything built using Textual) due to some dependencies not being ready for 3.12.

**Comment by mihaitodor** [comment]
Oh, good to know! Thank you for sharing those details. Python packaging is a bit of a pain that I’m still learning how to deal with. I’m happy to use `pyenv` instead.

**Comment by davep** [comment]
Aye, Python packing is *horrible*; although there does seem to be current development efforts coming forward that might finally clean stuff up (famous last words right?)

Meanwhile... eventually I'd like to wrap my head around the horror that is packing Python apps for homebrew; hopefully then installing something like oshit will be a wee bit easier. ;-)

**Comment by davep** [comment]
I've relaxed the allowed Python version now and pushed an update; looks like everything is playing friendly now.

**Comment by mihaitodor** [comment]
Awesome, that did the job. Thank you!
